#Befehl und Rückmeldungen + KPIs
# Schnittstelle, welche Nodes, welche Gruppen, welche Zustände + Routings
# Dient als Wörterbuch quasi gemeinsame Sprache vom DT, Server und Modell

ROOT_OBJECT = "Conveyor"
COMMANDS = "C"
RESPONSES = "R"
KPIS = "KPI"

STATE_STOPPED = "STOPPED"
STATE_RUNNING = "RUNNING"

COMMAND_RUN = "RUN"
COMMAND_MAIN_SPEED = "MAIN_SPEED"
COMMAND_TARGET_LANE = "TARGET_LANE"
COMMAND_RESET = "RESET"

RESPONSE_STATE = "STATE"
RESPONSE_SIMULATION_TIME = "SIMULATION_TIME"
RESPONSE_TICK = "TICK"
RESPONSE_LAST_EVENT = "LAST_EVENT"

KPI_THROUGHPUT_ALL = "THROUGHPUT_ALL"
KPI_THROUGHPUT_1 = "THROUGHPUT_LANE_1"
KPI_THROUGHPUT_2 = "THROUGHPUT_LANE_2"
KPI_THROUGHPUT_3 = "THROUGHPUT_LANE_3"
KPI_WIP = "WIP"

ROUTING_ROUND_ROBIN = "ROUND_ROBIN"
ROUTING_TARGET = "TARGET"
ROUTING_MODES = {ROUTING_ROUND_ROBIN,ROUTING_TARGET}




